# Generated by Django 2.2.3 on 2019-07-29 10:52

import booking.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audi_layout',
            options={'verbose_name': 'Audi_layout', 'verbose_name_plural': 'Audi_layouts'},
        ),
        migrations.AlterModelOptions(
            name='auditorium',
            options={'verbose_name': 'Auditorium', 'verbose_name_plural': 'Auditoriums'},
        ),
        migrations.AlterModelOptions(
            name='layouts',
            options={'verbose_name': 'Layout', 'verbose_name_plural': 'Layouts'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.RemoveField(
            model_name='layouts',
            name='auditorium',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_time',
        ),
        migrations.AddField(
            model_name='show',
            name='auditorium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Auditorium'),
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(null=True, validators=[booking.validation.validate_date_show]),
        ),
        migrations.AddField(
            model_name='show',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='layout_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Show'),
        ),
    ]
