# Generated by Django 2.2.3 on 2019-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190729_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
