# Generated by Django 2.2.3 on 2019-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_show_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='overview',
            field=models.TextField(default='Not available'),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.TextField(default='Not available'),
        ),
    ]
