# Generated by Django 2.2.3 on 2019-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190803_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='IMDB_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
