# Generated by Django 2.2.3 on 2019-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190803_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.AddField(
            model_name='movies',
            name='casts',
            field=models.ManyToManyField(blank=True, to='booking.Cast'),
        ),
    ]
