# Generated by Django 2.2.3 on 2019-08-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190803_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='casts',
        ),
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Cast')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Movies')),
            ],
        ),
    ]
